- name: configure catalogue component
  hosts: catalogue
  become: yes
  gather_facts: yes
  tasks:
    - name: disable default node js
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install Nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create the app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: create the roboshop user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: yes
        home: /app

    - name: download catalogue code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip


    - name: extract the catalogue code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: install npm dependencies
      community.general.npm:
        path: /app
        state: present

    - name: copy the catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start the catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes

    - name: copy the mongodb repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: check if the products are loaded or not
      ansible.builtin.command: mongosh --host mongodb-internal.doubtfree.online --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: output

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ output }}"

    - name: load the data
      ansible.builtin.command: mongosh --host mongodb-internal.doubtfree.online < /app/db/master-data.js
      when: output.rc != 0

    - name: restart the catalogue service
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: yes