- name: configure payment server
  hosts: payment
  become: yes
  gather_facts: yes
  tasks:
    - name: Install python 3 packages
      ansible.builtin.dnf:
        name: {{ item }}
        state: installed
      with_items:
        - python3
        - python3-devel
        - gcc

    - name: create an app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name:  create the roboshop user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: yes
        home: /app

    - name: download payment code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
        dest: /tmp/payment.zip

    - name: extract payment code
      ansible.builtin.unzip:
        src: /tmp/payment.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      ansible.builtin.pip:
        requirements: requirements.txt
        executable: pip3.9
        args:
          chdir: /app

    - name: copy payment service
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/payment.service

    - name: daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start payment service
      ansible.builtin.service:
        name: payment
        state: started
        enabled: yes
