- name: Create the rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
    - name: copy the rabbitmq repo file
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: Install the rabbitmq server
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: installed

    - name: enable and start the rabbitmq service
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: create rabbitmq user
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        permissions:
          - vhost: /
            configure_priv: .*
            read_priv: .*
            write_priv: .*
        state: present